server:
  port: 9010

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
#    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:80
#        namespace: jp
#        group: jp
    gateway:
      discovery:
        locator:
          enabled: true  #开启通过服务中心的自动根据 serviceId 创建路由的功能
      routes:
        - id: user-service             #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://user-service             #匹配后提供服务的路由地址
          predicates:
            - Path=/jpUser/**             #断言，路径相匹配的进行路由

        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/jpVideo/**
#  main:
#    web-application-type: reactive

#动态路由
#gateway:
#  routes:
#    config:
#      data-id: gateway-routes  #动态路由
#      group: shop
#      namespace: mdx

# 这个是 jwt 的配置
jwt:
  tokenHeader: Authorization
  secret: mdx-secrt000001
  expiration: 604800 #秒
  prefix: Bearer

# 不用登录就可以访问的接口
allowed:
  paths: /jpUser/auth/login