server:
  port: 9092

spring:
  application:
    name: configure-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:80
        namespace: mdx
        group: mdx

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jianpian?autoRec&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true #打印执行的sql语句，false则不打印sql
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

seata:
  tx-service-group: my_test_tx_group
  enabled: true
  registry:
    type: nacos
    nacos:
      application: mdx-seata-server  #注册在nacos服务名
      server-addr: localhost:8848
      group : mdx
      namespace: mdx #注册在nacos命名空间


