server:
  port: 9091

spring:
  application:
    name: video-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:80
#        namespace: b4d6d083-706f-481a-bb92-9e92bf88fcd0

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jianpian?autoRec&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    druid:
      test-while-idle: false


  jpa:
    show-sql: true #打印执行的sql语句，false则不打印sql
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

#feign:
#  sentinel:
#    enabled: true


